sudo: required
service:
  - docker

before_install:
  - docker build -t ravij/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ravij/react-test npm test  -- --coverage

after_success: 
  - docker build -t ravijoshi2209/multi-client ./client
  - docker build -t ravijoshi2209/multi-nginx ./nginx
  - docker build -t ravijoshi2209/multi-server ./server    
  - docker build -t ravijoshi2209/multi-worker ./worker
  #Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push these images to docker hub
  - docker push ravijoshi2209/multi-client
  - docker push ravijoshi2209/multi-nginx
  - docker push ravijoshi2209/multi-server
  - docker push ravijoshi2209/multi-worker


